#ifndef SPS_H
#define SPS_H

#include <utils.h>
#include <ptl.h>

// 7.3.2.4 Sequence parameter set RBSP syntax - Rec. ITU-T H.266 (V3) (09/2023)
typedef struct {
    uint_t sps_seq_parameter_set_id;
    uint_t sps_video_parameter_set_id;
    uint_t sps_max_sublayers_minus1;
    uint_t sps_chroma_format_idc;
    uint_t sps_log2_ctu_size_minus5;
    uint_t sps_ptl_dpb_hrd_params_present_flag;
    Profile_Tier_Level* ptl;
    uint_t sps_gdr_enabled_flag;
    uint_t sps_ref_pic_resampling_enabled_flag;
    uint_t sps_res_change_in_clvs_allowed_flag;
    uint_t sps_pic_width_max_in_luma_samples;
    uint_t sps_pic_height_max_in_luma_samples;
    uint_t sps_conformance_window_flag;
    uint_t sps_conf_win_left_offset;
    uint_t sps_conf_win_right_offset;
    uint_t sps_conf_win_top_offset;
    uint_t sps_conf_win_bottom_offset;
    uint_t sps_subpic_info_present_flag;
    uint_t sps_num_subpics_minus1;
    uint_t sps_independent_subpics_flag;
    uint_t sps_subpic_same_size_flag;
    uint_t* sps_subpic_ctu_top_left_x;
    uint_t* sps_subpic_ctu_top_left_y;
    uint_t* sps_subpic_width_minus1;
    uint_t* sps_subpic_height_minus1;
    uint_t* sps_subpic_treated_as_pic_flag;
    uint_t* sps_loop_filter_across_subpic_enabled_flag;
    uint_t sps_subpic_id_len_minus1;
    uint_t sps_subpic_id_mapping_explicitly_signalled_flag;
    uint_t sps_subpic_id_mapping_present_flag;
    uint_t* sps_subpic_id;
    uint_t sps_bitdepth_minus8;
    uint_t sps_entropy_coding_sync_enabled_flag;
    uint_t sps_entry_point_offsets_present_flag;
    uint_t sps_log2_max_pic_order_cnt_lsb_minus4;
    uint_t sps_poc_msb_cycle_flag;
    uint_t sps_poc_msb_cycle_len_minus1;
    uint_t sps_num_extra_ph_bytes;
    uint_t* sps_extra_ph_bit_present_flag;
    uint_t sps_num_extra_sh_bytes;
    uint_t* sps_extra_sh_bit_present_flag;
    uint_t sps_sublayer_dpb_params_flag;
    // dpb_parameters
    uint_t sps_log2_min_luma_coding_block_size_minus2;
    uint_t sps_partition_constraints_override_enabled_flag;
    uint_t sps_log2_diff_min_qt_min_cb_intra_slice_luma;
    uint_t sps_max_mtt_hierarchy_depth_intra_slice_luma;
    uint_t sps_log2_diff_max_bt_min_qt_intra_slice_luma;
    uint_t sps_log2_diff_max_tt_min_qt_intra_slice_luma;
    uint_t sps_qtbtt_dual_tree_intra_flag;
    uint_t sps_log2_diff_min_qt_min_cb_intra_slice_chroma;
    uint_t sps_max_mtt_hierarchy_depth_intra_slice_chroma;
    uint_t sps_log2_diff_max_bt_min_qt_intra_slice_chroma;
    uint_t sps_log2_diff_max_tt_min_qt_intra_slice_chroma;
    uint_t sps_log2_diff_min_qt_min_cb_inter_slice;
    uint_t sps_max_mtt_hierarchy_depth_inter_slice;
    uint_t sps_log2_diff_max_bt_min_qt_inter_slice;
    uint_t sps_log2_diff_max_tt_min_qt_inter_slice;
    uint_t sps_max_luma_transform_size_64_flag;
    uint_t sps_transform_skip_enabled_flag;
    uint_t sps_log2_transform_skip_max_size_minus2;
    uint_t sps_bdpcm_enabled_flag;
    uint_t sps_mts_enabled_flag;
    uint_t sps_explicit_mts_intra_enabled_flag;
    uint_t sps_explicit_mts_inter_enabled_flag;
    uint_t sps_lfnst_enabled_flag;
    uint_t sps_joint_cbcr_enabled_flag;
    uint_t sps_same_qp_table_for_chroma_flag;
    uint_t* sps_qp_table_start_minus26;
    uint_t* sps_num_points_in_qp_table_minus1;
    uint_t** sps_delta_qp_in_val_minus1;
    uint_t** sps_delta_qp_diff_val;
    uint_t sps_sao_enabled_flag;
    uint_t sps_alf_enabled_flag;
    uint_t sps_ccalf_enabled_flag;
    uint_t sps_lmcs_enabled_flag;
    uint_t sps_weighted_pred_flag;
    uint_t sps_weighted_bipred_flag;
    uint_t sps_long_term_ref_pics_flag;
    uint_t sps_inter_layer_prediction_enabled_flag;
    uint_t sps_idr_rpl_present_flag;
    uint_t sps_rpl1_same_as_rpl0_flag;
    uint_t* sps_num_ref_pic_lists;
    // ref_pic_list_struct
    uint_t sps_ref_wraparound_enabled_flag;
    uint_t sps_temporal_mvp_enabled_flag;
    uint_t sps_sbtmvp_enabled_flag;
    uint_t sps_amvr_enabled_flag;
    uint_t sps_bdof_enabled_flag;
    uint_t sps_bdof_control_present_in_ph_flag;
    uint_t sps_smvd_enabled_flag;
    uint_t sps_dmvr_enabled_flag;
    uint_t sps_dmvr_control_present_in_ph_flag;
    uint_t sps_mmvd_enabled_flag;
    uint_t sps_mmvd_fullpel_only_enabled_flag;
    uint_t sps_six_minus_max_num_merge_cand;
    uint_t sps_sbt_enabled_flag;
    uint_t sps_affine_enabled_flag;
    uint_t sps_five_minus_max_num_subblock_merge_cand;
    uint_t sps_6param_affine_enabled_flag;
    uint_t sps_affine_amvr_enabled_flag;
    uint_t sps_affine_prof_enabled_flag;
    uint_t sps_prof_control_present_in_ph_flag;
    uint_t sps_bcw_enabled_flag;
    uint_t sps_ciip_enabled_flag;
    uint_t sps_gpm_enabled_flag;
    uint_t sps_max_num_merge_cand_minus_max_num_gpm_cand;
    uint_t sps_log2_parallel_merge_level_minus2;
    uint_t sps_isp_enabled_flag;
    uint_t sps_mrl_enabled_flag;
    uint_t sps_mip_enabled_flag;
    uint_t sps_cclm_enabled_flag;
    uint_t sps_chroma_horizontal_collocated_flag;
    uint_t sps_chroma_vertical_collocated_flag;
    uint_t sps_palette_enabled_flag;
    uint_t sps_act_enabled_flag;
    uint_t sps_min_qp_prime_ts;
    uint_t sps_ibc_enabled_flag;
    uint_t sps_six_minus_max_num_ibc_merge_cand;
    uint_t sps_ladf_enabled_flag;
    uint_t sps_num_ladf_intervals_minus2;
    uint_t sps_ladf_lowest_interval_qp_offset;
    uint_t* sps_ladf_qp_offset;
    uint_t* sps_ladf_delta_threshold_minus1;
    uint_t sps_explicit_scaling_list_enabled_flag;
    uint_t sps_scaling_matrix_for_lfnst_disabled_flag;
    uint_t sps_scaling_matrix_for_alternative_colour_space_disabled_flag;
    uint_t sps_scaling_matrix_designated_colour_space_flag;
    uint_t sps_dep_quant_enabled_flag;
    uint_t sps_sign_data_hiding_enabled_flag;
    uint_t sps_virtual_boundaries_enabled_flag;
    uint_t sps_virtual_boundaries_present_flag;
    uint_t sps_num_ver_virtual_boundaries;
    uint_t* sps_virtual_boundary_pos_x_minus1;
    uint_t sps_num_hor_virtual_boundaries;
    uint_t* sps_virtual_boundary_pos_y_minus1;
    uint_t sps_timing_hrd_params_present_flag;
    // general_timing_hrd_parameters
    uint_t sps_sublayer_cpb_params_present_flag;
    // ols_timing_hrd_parameters
    uint_t sps_field_seq_flag;
    uint_t sps_vui_parameters_present_flag;
    uint_t sps_vui_payload_size_minus1;
    // uint_t sps_vui_alignment_zero_bit
    // vui_payload
    uint_t sps_extension_flag;
    uint_t sps_range_extension_flag;
    uint_t sps_extension_7bits;
    // sps_range_extension
    uint_t sps_extension_data_flag;
} Sequence_Parameter_Set;

Sequence_Parameter_Set* seq_parameter_set_rbsp();

void freeSPS(Sequence_Parameter_Set* sps);
void printSPS(Sequence_Parameter_Set* sps);

#endif // SPS_H